### ISSUE TITLE
(暫時)取得 teia/watermap 的管理權限

### ISSUE THREAD

**Issue by voidlps** [voidlps/watermap-data-community#6]

**Comment by voidlps** [comment]
初步詢問：being 說可以直接暫時給我他的 github access (login then let me access)，來完成必要的操作

**Comment by voidlps** [comment]
https://www.facebook.com/groups/1255977671181394/permalink/2732301906882289/
陳瑞賓 我同意先關閉回報功能，先避免造成osm的困擾。後續社群有新的想法，當做另案談。需要怎麼配合，再跟我說。

**Comment by pm5** [comment]
取得權限的進度如何？

**Comment by voidlps** [comment]
done
![Screenshot from 2020-03-06 10-34-52](https://user-images.githubusercontent.com/3744683/76044776-44aad180-5f96-11ea-9d85-fdae072c1d8f.png)
